#!/bin/bash
# Harden SSH Configuration

set -euo pipefail

SSH_CONFIG="/etc/ssh/sshd_config"
SSH_CONFIG_BACKUP="${SSH_CONFIG}.backup-$(date +%Y%m%d)"

log() {
    echo "[SSH-HARDEN] $1"
}

# Backup current config
cp "$SSH_CONFIG" "$SSH_CONFIG_BACKUP"
log "Backed up SSH config to $SSH_CONFIG_BACKUP"

# Apply hardening settings
cat > "$SSH_CONFIG" << 'SSHEOF'
# SSH Hardening Configuration
# Generated by server-hardening script

# Port and protocol
Port 22
Protocol 2

# Authentication
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

# Disable unnecessary features
X11Forwarding no
PrintMotd no
AcceptEnv LANG LC_*

# Timeout settings
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 60

# Limit users (adjust as needed)
# AllowUsers your-username

# Subsystem
Subsystem sftp /usr/lib/openssh/sftp-server
SSHEOF

# Validate configuration
if sshd -t; then
    log "✓ SSH configuration valid"
    systemctl restart sshd
    log "✓ SSH service restarted"
else
    log "✗ SSH configuration invalid! Restoring backup..."
    cp "$SSH_CONFIG_BACKUP" "$SSH_CONFIG"
    exit 1
fi

log "SSH hardening complete"
